/**
 * Service Worker registration with update detection.
 *
 * Registers the SW generated by next-pwa and listens for the "waiting" state
 * which indicates a new version is available. Exposes a callback so the UI
 * can show a non-blocking update banner (Req 6.7).
 */

type SwUpdateCallback = (registration: ServiceWorkerRegistration) => void;

let onUpdateCallback: SwUpdateCallback | null = null;

/**
 * Set the callback that fires when a new SW is waiting to activate.
 */
export function onSwUpdate(cb: SwUpdateCallback): void {
  onUpdateCallback = cb;
}

/**
 * Tell the waiting SW to skip waiting and take over.
 * After the new SW activates, reload the page so the user gets the fresh shell.
 */
export function applySwUpdate(registration: ServiceWorkerRegistration): void {
  const waiting = registration.waiting;
  if (waiting) {
    waiting.postMessage({ type: "SKIP_WAITING" });
  }
}

/**
 * Register the service worker and wire up update detection.
 * Call this once from the root layout (client component).
 */
export async function registerServiceWorker(): Promise<void> {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) {
    return;
  }

  try {
    const registration = await navigator.serviceWorker.register("/sw.js", {
      scope: "/",
    });

    // If there's already a waiting worker on first load, notify immediately
    if (registration.waiting) {
      onUpdateCallback?.(registration);
      return;
    }

    // Listen for new installing workers
    registration.addEventListener("updatefound", () => {
      const installing = registration.installing;
      if (!installing) return;

      installing.addEventListener("statechange", () => {
        if (installing.state === "installed" && navigator.serviceWorker.controller) {
          // New SW installed and waiting — an update is available
          onUpdateCallback?.(registration);
        }
      });
    });

    // When the controlling SW changes (after skipWaiting), reload the page
    let refreshing = false;
    navigator.serviceWorker.addEventListener("controllerchange", () => {
      if (refreshing) return;
      refreshing = true;
      window.location.reload();
    });
  } catch (error) {
    console.error("[SW] Registration failed:", error);
  }
}
